version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: go_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: amir
      POSTGRES_PASSWORD: 1379
      POSTGRES_DB: note_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
